# Generated by Django 5.1.4 on 2024-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                default="default/default_avatar.png", upload_to="profile_pics"
            ),
        ),
    ]
