# Generated by Django 5.1.4 on 2024-12-27 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0003_propertycomment_parent_commentlike_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="District Name"),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Governorate Name"),
                ),
            ],
            options={
                "verbose_name": "Governorate",
                "verbose_name_plural": "Governorates",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[
                    ("YER", "Yemeni Rial"),
                    ("USD", "US Dollar"),
                    ("SAR", "Saudi Riyal"),
                ],
                default="YER",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="floor_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Floor Number"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="kitchens",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Kitchens"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="living_rooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Living Rooms"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="majlis",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Majlis"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="map_location",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Map Location"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="neighborhood",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Neighborhood/Street",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="number_of_floors",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Floors"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Bathrooms"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Number of Bedrooms"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="properties.district",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="governorate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="properties.governorate",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="governorate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="properties",
                to="properties.governorate",
            ),
        ),
    ]
