# Generated by Django 5.1.4 on 2024-12-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0004_district_governorate_property_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="councils_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Councils"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="halls_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Halls"
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="rooms_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Rooms"
            ),
        ),
    ]
