# Generated by Django 5.1.4 on 2024-12-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("properties", "0005_property_councils_count_property_halls_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="area_measurment",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="currency",
            field=models.CharField(
                choices=[
                    ("YER", "ريال يمني "),
                    ("USD", "دولار"),
                    ("SAR", " ريال سعودي"),
                ],
                default="YER",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "للبيع"), ("rent", "للإجار")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "شقة"),
                    ("house", "منزل"),
                    ("villa", "فلة"),
                    ("land", "أرض"),
                    ("commercial", "دكان"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyrequest",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "للبيع"), ("rent", "للإجار")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="propertyrequest",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("apartment", "شقة"),
                    ("house", "منزل"),
                    ("villa", "فلة"),
                    ("land", "أرض"),
                    ("commercial", "دكان"),
                ],
                max_length=20,
            ),
        ),
    ]
