# Generated by Django 5.1.4 on 2024-12-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0006_property_area_measurment_alter_property_currency_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="area_measurment",
            field=models.CharField(
                choices=[("meter", "متر مربع"), ("labinh", "لبنه"), ("q", "قصبة")],
                max_length=20,
            ),
        ),
    ]
